# Generated by Django 5.1 on 2024-09-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0002_remove_role_users_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
