# Generated by Django 5.1 on 2024-10-24 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('review', 'En Revisión'), ('published', 'Publicado'), ('rejected', 'Rechazado'), ('inactive', 'Inactivo')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision_started_at', models.DateTimeField(blank=True, null=True)),
                ('revision_ended_at', models.DateTimeField(blank=True, null=True)),
                ('published_started_at', models.DateField(blank=True, null=True)),
                ('likes', models.PositiveIntegerField(default=0)),
                ('dislikes', models.PositiveIntegerField(default=0)),
                ('numero_visitas', models.PositiveIntegerField(default=0)),
                ('inactivated_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('texto', 'Texto'), ('multimedia', 'Multimedia')], max_length=20)),
                ('content_text', models.TextField(blank=True, null=True)),
                ('multimedia', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('top', models.CharField(default='0px', max_length=10)),
                ('left', models.CharField(default='0px', max_length=10)),
                ('width', models.CharField(default='200px', max_length=10)),
                ('height', models.CharField(default='100px', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked', models.BooleanField(default=False)),
                ('disliked', models.BooleanField(default=False)),
            ],
        ),
    ]
