# Generated by Django 5.1 on 2024-09-11 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Categorias', '0001_initial'),
        ('Plantillas', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('review', 'En Revisión'), ('published', 'Publicado'), ('rejected', 'Rechazado'), ('inactive', 'Inactivo')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Categorias.categorias')),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Plantillas.plantilla')),
            ],
        ),
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('texto', 'Texto'), ('multimedia', 'Multimedia')], max_length=20)),
                ('content_text', models.TextField(blank=True, null=True)),
                ('multimedia', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('top', models.CharField(default='0px', max_length=10)),
                ('left', models.CharField(default='0px', max_length=10)),
                ('width', models.CharField(default='200px', max_length=10)),
                ('height', models.CharField(default='100px', max_length=10)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='content.content')),
            ],
        ),
    ]
