# Generated by Django 5.1 on 2024-09-03 06:15
from django.db import migrations

def add_default_categories(apps, schema_editor):
    Category = apps.get_model('content', 'Category')
    Category.objects.create(name='Categoría 1', description='Descripción de la Categoría 1')
    Category.objects.create(name='Categoría 2', description='Descripción de la Categoría 2')
    Category.objects.create(name='Categoría 3', description='Descripción de la Categoría 3')

class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),  # Reemplaza esto con el nombre de la última migración en content
    ]

    operations = [
        migrations.RunPython(add_default_categories),
    ]
