# Generated by Django 5.1 on 2024-10-11 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_comentario'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='dislikes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='content',
            name='likes',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
