# Generated by Django 5.1 on 2024-09-06 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plantillas', '0003_alter_bloque_height_alter_bloque_width'),
        ('content', '0002_add_default_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Plantillas.plantilla'),
        ),
    ]
