# Generated by Django 5.1 on 2024-11-08 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='shared_count',
            field=models.IntegerField(default=0),
        ),
    ]
