# Generated by Django 5.1 on 2024-12-04 17:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_content_shared_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentblock',
            name='multimedia',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
