# Generated by Django 5.1 on 2024-09-08 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_content_plantilla'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_type', models.CharField(choices=[('texto', 'Texto'), ('multimedia', 'Multimedia')], max_length=20)),
                ('content_text', models.TextField(blank=True, null=True)),
                ('multimedia', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('top', models.CharField(default='0px', max_length=10)),
                ('left', models.CharField(default='0px', max_length=10)),
                ('width', models.CharField(default='200px', max_length=10)),
                ('height', models.CharField(default='100px', max_length=10)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='content.content')),
            ],
        ),
    ]
