# Generated by Django 5.1 on 2024-10-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_content_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='revision_ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='content',
            name='revision_started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
