# Generated by Django 5.1 on 2024-10-23 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_content_revision_ended_at_and_more'),
        ('content', '0006_rename_autor_content_author'),
    ]

    operations = [
    ]
