# Generated by Django 5.1 on 2024-10-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_content_revision_ended_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='published_started_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
