# Generated by Django 5.1 on 2024-10-23 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_merge_20241023_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='author',
            new_name='autor',
        ),
        migrations.AddField(
            model_name='content',
            name='published_started_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
