# Generated by Django 5.1 on 2024-10-24 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_content_inactivated_at_content_published_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='numero_visitas',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
