# Generated by Django 5.1 on 2024-09-15 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('revision', 'Revisión'), ('publicado', 'Publicado'), ('rechazado', 'Rechazado')], default='borrador', max_length=10)),
            ],
        ),
    ]
