# Generated by Django 5.1 on 2024-09-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historial',
            name='version',
            field=models.IntegerField(default=1),
        ),
    ]
