# Generated by Django 5.1 on 2024-12-01 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historial',
            name='accion_detalle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
