# Generated by Django 5.1 on 2024-09-11 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('contenido', models.TextField(blank=True)),
                ('multimedia', models.FileField(blank=True, null=True, upload_to='uploads/')),
                ('posicion_top', models.CharField(max_length=50)),
                ('posicion_left', models.CharField(max_length=50)),
                ('width', models.CharField(blank=True, default='200px', max_length=50)),
                ('height', models.CharField(blank=True, default='100px', max_length=50)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='Plantillas.plantilla')),
            ],
        ),
    ]
