# Generated by Django 5.1 on 2024-09-05 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plantillas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bloque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=50)),
                ('contenido', models.TextField()),
                ('posicion_top', models.CharField(max_length=50)),
                ('posicion_left', models.CharField(max_length=50)),
                ('width', models.CharField(max_length=50)),
                ('height', models.CharField(max_length=50)),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Plantillas.plantilla')),
            ],
        ),
    ]
