# Generated by Django 5.1 on 2024-09-06 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plantillas', '0002_bloque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloque',
            name='height',
            field=models.CharField(blank=True, default='100px', max_length=50),
        ),
        migrations.AlterField(
            model_name='bloque',
            name='width',
            field=models.CharField(blank=True, default='200px', max_length=50),
        ),
    ]
