# Generated by Django 5.1 on 2024-09-06 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plantillas', '0003_alter_bloque_height_alter_bloque_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloque',
            name='plantilla',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bloques', to='Plantillas.plantilla'),
        ),
    ]
