# Generated by Django 5.1 on 2024-09-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Plantillas', '0004_alter_bloque_plantilla'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloque',
            name='multimedia',
            field=models.FileField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='bloque',
            name='contenido',
            field=models.TextField(blank=True),
        ),
    ]
